#
# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
- name: Create secrets/oraoper Directory
  ansible.builtin.file:
    mode: "0700"
    path: "{{ kubernetes_dir }}/secrets/oraoper"
    state: directory

- name: Create Cloud Database Secrets
  when: vars.database_oracle_dbs is defined
  block:
    - name: Create Bind Database Manifests
      when: common_oci_env.compartment_ocid is defined
      ansible.builtin.template:
        mode: "0600"
        src: oraoper_adb.yaml.j2
        dest: "{{ kubernetes_dir }}/secrets/oraoper/{{ dbname | lower }}.yaml"
      loop: "{{ vars.database_oracle_dbs }}"
      loop_control:
        loop_var: dbname

    - name: Create Provision Database Manifests
      when: common_oci_env.compartment_ocid is not defined
      ansible.builtin.template:
        mode: "0600"
        src: oraoper_sidb.yaml.j2
        dest: "{{ kubernetes_dir }}/secrets/oraoper/{{ dbname | lower }}.yaml"
      loop: "{{ vars.database_oracle_dbs }}"
      loop_control:
        loop_var: dbname

    - name: Create Database Kustomization
      ansible.builtin.template:
        mode: "0600"
        src: oraoper_kustomization.yaml.j2
        dest: "{{ kubernetes_dir }}/secrets/oraoper/kustomization.yaml"

    ###################################################################
    # Database Specific Secrets                                       #
    ###################################################################
    - name: Create secrets/database Directory
      ansible.builtin.file:
        mode: "0700"
        path: "{{ kubernetes_dir }}/secrets/database"
        state: directory

    - name: Create Database Secret Kustomization
      ansible.builtin.template:
        mode: "0600"
        src: secret_kustomization.yaml.j2
        dest: "{{ kubernetes_dir }}/secrets/database/kustomization.yaml"

    - name: Create tnsnames.ora Secret
      when: common_oci_env.compartment_ocid is not defined
      ansible.builtin.template:
        mode: "0600"
        src: tns_admin.yaml.j2
        dest: "{{ kubernetes_dir }}/secrets/database/{{ dbname | lower }}-tns-admin.yaml"
      loop: "{{ vars.database_oracle_dbs }}"
      loop_control:
        loop_var: dbname
