apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics-server
labels:
  - pairs:
      app.kubernetes.io/part-of: common
      app.kubernetes.io/version: 0.6.4
      helm-version: 3.11.0
resources:
  - namespace--metrics-server.yaml
  - ../../../../secrets/tls-certificate
# Helm Chart
helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server
    version: 3.11.0
    releaseName: metrics-server
    namespace: metrics-server
    includeCRDs: true
    valuesFile: values.yaml
