# Copyright © 2023, Oracle and/or its affiliates.
# All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "ORDS-K8S Proof of Concept"
description: "ORDS-K8S Proof of Concept"
schemaVersion: 1.1.0
version: "20231011"

source:
  type: marketplace
  reference: 138759852

locale: "en"

variableGroups:
  #########################################################################
  # Hidden
  #########################################################################
  - title: "Default Hidden"
    variables:
      - ociTenancyOcid
      - ociRegionIdentifier
      - ociUserOcid
      - current_user_ocid
      - fingerprint
      - resPathUserPublicKey
      - resUserPublicKey
    visible: false

  - title: "Hidden (Defaults)"
    variables:
      - orm_install
      - run_ansible
      - oke_version
      - service_lb_ingress
      - byo_auth_token
      - worker_nsg_lockdown
    visible: false

  #########################################################################
  # General
  #########################################################################
  - title: "General Configuration"
    variables:
      - ociCompartmentOcid
      - label_prefix
    visible: true

  #########################################################################
  # BYO VCN
  #########################################################################
  - title: "Network Options"
    variables:
      - byo_vcn
      - byo_vcn_compartment
      - ociVcnOcid
      - byo_private_subnet_ocid
      - byo_public_subnet_ocid
    visible: true

  #########################################################################
  # Kubernetes Cluster
  #########################################################################
  - title: "Kubernetes Cluster Options"
    variables:
      - oke_api_is_public
      - oke_api_endpoint_allowed_cidrs
      - horizontal_pod_autoscaling
      - oke_worker_pool_size
      - oke_node_worker_shape
      - oke_node_worker_ocpu
    visible: true

  #########################################################################
  # Load Balancer
  #########################################################################
  - title: "Load Balancers Options"
    variables:
      - service_lb_is_public
      - service_lb_allowed_cidrs
      - service_lb_allowed_ports
      - service_lb_min_shape
      - service_lb_max_shape
    visible: true

  #########################################################################
  # Database
  #########################################################################
  - title: "Database Options"
    variables:
      - adb_compute_model
      - adb_networking
      - adb_whitelist_cidrs
      - adb_bastion_cidrs
      - adb_ecpu_core_count
      - adb_ocpu_core_count
      - adb_is_cpu_auto_scaling_enabled
      - adb_data_storage_size_in_gb
      - adb_data_storage_size_in_tbs
      - adb_is_storage_auto_scaling_enabled
      - adb_license_model
      - adb_edition
      - adb_create_bucket
    visible: true

###########################################################################
variables:

  ociCompartmentOcid:
    type: oci:identity:compartment:id
    title: "Compartment"
    required: true

  label_prefix:
    type: string
    title: "Application Name"
    pattern: "^$|^[a-zA-Z0-9]{1,12}$"
    required: false

  #########################################################################
  byo_vcn:
    type: boolean
    title: "Bring Your Own Virtual Cloud Network?"
    default: false
    visible: true

  byo_vcn_compartment:
    title: "Virtual Cloud Network Compartment"
    description: "BYO VCN Compartment"
    type: oci:identity:compartment:id
    required: true
    default: ociCompartmentOcid
    visible: byo_vcn

  ociVcnOcid:
    type: oci:core:vcn:id
    title: "Virtual Cloud Network (VCN)"
    description: "BYO VCN Resource"
    dependsOn:
      compartmentId: byo_vcn_compartment
    required: false
    default: ""
    visible: byo_vcn

  byo_public_subnet_ocid:
    type: oci:core:subnet:id
    title: "Public Subnet"
    description: "BYO Public Subnet - Leave Blank to Create"
    dependsOn:
      compartmentId: byo_vcn_compartment
      vcnId: ociVcnOcid
      hidePublicSubnet: false
      hidePrivateSubnet: true
    required: false
    default: ""
    visible: byo_vcn

  byo_private_subnet_ocid:
    type: oci:core:subnet:id
    title: "Private Subnet"
    description: "BYO Private Subnet - Leave Blank to Create"
    dependsOn:
      compartmentId: byo_vcn_compartment
      vcnId: ociVcnOcid
      hidePublicSubnet: true
      hidePrivateSubnet: false
    required: false
    default: ""
    visible: byo_vcn

  #########################################################################
  oke_api_is_public:
    type: boolean
    title: "Public API Endpoint?"
    required: true
    default: true

  oke_api_endpoint_allowed_cidrs:
    type: array
    title: "API Endpoint Access Control"
    required: true
    default: "0.0.0.0/0"
    pattern: "$|((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])(,?)( ?)){1,}$"
    visible: oke_api_is_public

  #########################################################################
  horizontal_pod_autoscaling:
    type: boolean
    title: "Enable Horizontal Pod Scaling?"
    description: "Allow horizontal pod scaling within a Node Pool"
    required: true
    default: false
    visible: false

  oke_worker_pool_size:
    type: integer
    title: "Node Pool Workers"
    required: true
    minimum: 1
    maximum: 80
    multipleOf: 1
    default: 2

  oke_node_worker_shape:
    type: enum
    title: "Node Pool Worker Shape"
    required: true
    default: "VM.Standard.E4.Flex"
    enum:
      - "VM.Standard.E4.Flex"
      - "VM.Standard3.Flex"

  oke_node_worker_ocpu:
    type: integer
    title: "Node Workers OCPU"
    required: true
    minimum: 1
    maximum: 64
    multipleOf: 1
    default: 1

  #########################################################################
  service_lb_is_public:
    type: boolean
    title: "Public Load Balancer?"
    default: true

  service_lb_allowed_cidrs:
    type: array
    title: "Public Load Balancer Access Control"
    required: true
    default: "0.0.0.0/0"
    pattern: "((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])(,?)( ?)){1,}$"
    visible: service_lb_is_public

  service_lb_allowed_ports:
    type: array
    title: "Load Balancer Ports Exposed"
    required: true
    default: "80, 443"
    pattern: "^(((6553[0-5])|(655[0-2][0-9])|(65[0-4][0-9]{2})|(6[0-4][0-9]{3})|([1-5][0-9]{4})|([0-5]{0,5})|([0-9]{1,4}))(,?)( ?)){1,}$"
    visible: service_lb_is_public

  service_lb_min_shape:
    type: integer
    title: "Minimum Load Balancer Bandwidth (Mbps)"
    required: true
    minimum: 10
    maximum: 10
    multipleOf: 10
    default: 10
    visible: service_lb_is_public

  service_lb_max_shape:
    type: integer
    title: "Maximum Load Balancer Bandwidth (Mbps)"
    required: true
    minimum: 10
    maximum: 8000
    multipleOf: 10
    default: 100
    visible: service_lb_is_public

  #########################################################################
  adb_compute_model:
    type: enum
    title: "Autonomous Database Compute Model"
    required: true
    default: "ECPU"
    enum:
      - "OCPU"
      - "ECPU"

  adb_networking:
    type: enum
    title: "Autonomous Database Network Access"
    required: true
    default: "SECURE_ACCESS"
    enum:
      - "PRIVATE_ENDPOINT_ACCESS"
      - "SECURE_ACCESS"

  adb_bastion_cidrs:
    type: array
    title: "ADB Bastion Service Access Control"
    required: true
    default: "0.0.0.0/0"
    pattern: "((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])(,?)( ?)){1,}$"
    visible:
      and:
        - eq:
            - adb_networking
            - PRIVATE_ENDPOINT_ACCESS

  adb_create_bucket:
    type: boolean
    title: "Create an Object Storage Bucket for ADB?"
    required: true
    default: false

  adb_data_storage_size_in_gb:
    type: number
    title: "Autonomous Database Data Storage Size (GB)"
    description: ""
    required: true
    minimum: 20
    maximum: 393216
    multipleOf: 1
    default: 20
    visible:
      and:
        - eq:
            - adb_compute_model
            - ECPU

  adb_data_storage_size_in_tbs:
    type: number
    title: "Autonomous Database Data Storage Size (TB)"
    description: ""
    required: true
    minimum: 1
    maximum: 384
    multipleOf: 1
    default: 1
    visible:
      and:
        - eq:
            - adb_compute_model
            - OCPU

  adb_ecpu_core_count:
    type: number
    title: "Autonomous Database ECPU Core Count"
    required: true
    minimum: 2
    multipleOf: 1
    default: 2
    visible:
      and:
        - eq:
            - adb_compute_model
            - ECPU

  adb_edition:
    type: enum
    title: "Oracle Database Edition"
    required: true
    default: "ENTERPRISE_EDITION"
    enum:
      - "ENTERPRISE_EDITION"
      - "STANDARD_EDITION"
    visible:
      and:
        - eq:
            - adb_license_model
            - BRING_YOUR_OWN_LICENSE

  adb_is_cpu_auto_scaling_enabled:
    type: boolean
    title: "Allow Autonomous Database CPU Auto Scaling? (3x CPU)"
    required: true
    default: false

  adb_is_storage_auto_scaling_enabled:
    type: boolean
    title: "Allow Autonomous Database Storage Auto Scaling?"
    required: true
    default: false

  adb_license_model:
    type: enum
    title: "Autonomous Database License Model"
    required: true
    default: "LICENSE_INCLUDED"
    enum:
      - "LICENSE_INCLUDED"
      - "BRING_YOUR_OWN_LICENSE"

  adb_ocpu_core_count:
    type: number
    title: "Autonomous Database OCPU Core Count"
    required: true
    minimum: 1
    multipleOf: 1
    default: 1
    visible:
      and:
        - eq:
            - adb_compute_model
            - OCPU

  adb_whitelist_cidrs:
    type: array
    title: "ADB Access Control"
    required: true
    default: "0.0.0.0/0"
    pattern: "((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])(,?)( ?)){1,}$"
    visible:
      and:
        - eq:
            - adb_networking
            - SECURE_ACCESS

###########################################################################
# Output Groups
###########################################################################
outputGroups:
  - title: "Access Your OKE Cluster"
    outputs:
      - kubeconfig_cmd
    visible: true

  - title: "Access the Application"
    outputs:
      - ords_uri
    visible: true

  - title: "Autonomous Database"
    outputs:
      - adb_name
      - adb_ip
      - adb_admin_password
    visible: true
###########################################################################
outputs:
  adb_ip:
    title: "Autonomous Database Private IP"
    type: string
    visible: true

  adb_name:
    title: "Autonomous Database Name"
    type: string
    visible: true

  adb_admin_password:
    title: "Autonomous Database ADMIN Password"
    type: string
    visible: true

  kubeconfig_cmd:
    title: "Generate the kubeconfig"
    type: copyableString
    visible: true
