apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oracle-database-operator-system
labels:
  - pairs:
      app.kubernetes.io/name: oracle-database-operator-controller-manager
      app.kubernetes.io/part-of: database
      app.kubernetes.io/version: "1.0.0"
    includeTemplates: true 
resources:
  - oracle-database-operator.yaml