#
# Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
---
database_oracle_dbs: ["${baas_db}"]
database_default_db: ${baas_db}
${baas_db}: # noqa: var-naming[pattern]
  username: "${username}"
  password: "${password}"
  service: "${service}"
  ocid: "${adb_ocid}"
