#
# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
---
- name: Set Infrastructure
  tags: [always]
  ansible.builtin.set_fact:
    overlay_env: oci

- name: Set Active Applications
  ansible.builtin.set_fact:
    active_applications: "['common', 'database', 'default']"

- name: Set oci_terraform_dir
  ansible.builtin.set_fact:
    oci_terraform_dir: "{{ playbook_dir ~ '/../' }}"

- name: Set kubernetes_dir
  ansible.builtin.set_fact:
    kubernetes_dir: "{{ playbook_dir ~ '/../kubernetes' }}"

- name: Set manifests_dir
  ansible.builtin.set_fact:
    manifests_dir: "{{ kubernetes_dir ~ '/manifests' }}"

- name: Set images_dir
  ansible.builtin.set_fact:
    images_dir: "{{ playbook_dir ~ '/../images' }}"

- name: Set OCI_CLI_KEY_FILE
  when: common_oci_env | length > 0
  ansible.builtin.set_fact:
    common_oci_env: "{{ common_oci_env | combine( { 'OCI_CLI_KEY_FILE': oci_terraform_dir ~ '/' ~ common_private_key_file } ) }}"
