apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: do_not_define
labels:
  - pairs:
      app.kubernetes.io/part-of: database
      app.kubernetes.io/version: "1.12.3"
resources:
  - cert-manager.yaml
  # - clusterissuer--letsencrypt.yaml
