apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: registry-pull-auth
    type: "kubernetes.io/dockerconfigjson"
    files:
      - .dockerconfigjson=files/registry_pull_auth
  - name: registry-auth
    type: "kubernetes.io/dockerconfigjson"
    files:
      - .dockerconfigjson=files/registry_pull_auth
  - name: registry-push-auth
    type: "kubernetes.io/dockerconfigjson"
    files:
      - .dockerconfigjson=files/registry_push_auth
  - name: registry-login
    type: "Opaque"
    literals:
      - registry.push_url='<~<~ registry_push_url ~>~>'
      - registry.pull_url='<~<~ registry_pull_url ~>~>'
      - registry.username='<~<~ registry_username ~>~>'
      - registry.password='<~<~ registry_password ~>~>'
      - registry.compartment='<~<~ common_oci_env.compartment_ocid | default("N/A") ~>~>'