apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
labels:
  - pairs:
      app.kubernetes.io/part-of: common
      app.kubernetes.io/version: 1.9.6
      helm-version: 4.9.1
resources:
  - namespace--ingress-nginx.yaml
  - ../../../../secrets/tls-certificate
# Helm Chart
helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.9.1
    releaseName: ingress-nginx
    namespace: ingress-nginx
    includeCRDs: true
    valuesFile: values.yaml
images:
  - name: "registry.k8s.io/ingress-nginx/controller"
    newTag: "v1.9.6"
    newName: "{{ registry_pull_url }}/controller"
  - name: "registry.k8s.io/ingress-nginx/kube-webhook-certgen"
    newTag: "v20231226-1a7112e06"
    newName: "{{ registry_pull_url }}/kube-webhook-certgen"