apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
labels:
  - pairs:
      app.kubernetes.io/part-of: common
      app.kubernetes.io/version: 1.8.1
      helm-version: 4.7.1
resources:
  - namespace--ingress-nginx.yaml
  - ../../../../secrets/tls-certificate
# Helm Chart
helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.7.1
    releaseName: ingress-nginx
    namespace: ingress-nginx
    includeCRDs: true
    valuesFile: values.yaml
