apiVersion: v1
kind: Service
metadata:
  name: ords-svc
spec:
  selector:
    app.kubernetes.io/name: ords
  ports:
    - name: ords-svc-port
      protocol: TCP
      port: 80
      targetPort: ords-port
